### ISSUE TITLE
Impossible to set language

### ISSUE THREAD

**Issue by Aurielle** [iPublikuj/form-datetime#1]
The language for a control can't be set in any reasonable way without hacking the whole thing or inheriting the classes. That's because the language can only be set in constructor, which means the default (en) is used in extension method definition and the classes themselves don't have getter/setter to change it.

So in the meantime, I need to do this:

``` php
/** @var DateTime $start */
$start = $form['start'];
$property = $start->getReflection()->getProperty('language');
$property->setAccessible(TRUE);
$property->setValue($start, 'cs');
```

**Comment by akadlec** [comment]
Ok, now you can use setter for this.
