### ISSUE TITLE
Fields discard Nette validation rules

### ISSUE THREAD

**Issue by Aurielle** [iPublikuj/form-datetime#2]
Overloaded method `addRule()` in BaseControl makes every basic Nette rule non-functional, because there's no else clause to apply them. My use case:

``` php
$form->addDateTimePicker('end', 'front.timeblocks.end')
    ->setRequired('front.timeblocks.validation.endRequired')
    ->addRule(~$form::EQUAL, 'front.timeblocks.validation.zeroLength', $form['start']);
```

This use is perfectly valid and works as expected with added else clause.

**Comment by akadlec** [comment]
Missing else is added. Next time please create a pull request.
