### ISSUE TITLE
Nette 2.4 compatibility

### ISSUE THREAD

**Issue by MartinMystikJonas** [iPublikuj/form-datetime#7]
I just found out this library does not support Nette 2.4. What plans do you have with this lib? Should I prepare PR with compatibility fixes? Or if this lib is abbandoned should I create my own fork?

**Comment by akadlec** [comment]
If you have time, just create PR and i will merge it :)

**Comment by MartinMystikJonas** [comment]
Fine I will prepare it.

I would like to discuss two more minor changes we need to be able to use this component in one specific context (as filter in datagrid).

1) If string format passed to setValue does not match specified format try to use it as default DateTime constructor parameter (because we persist return value of getValue, which is DateTime, which is serialized to ISO format string  ant then use it in setValue)
2) For Date input always set time to 00:00:00 (currently there is current local time left which makes it unpredictable)

Whould I make it as separate PRs or can I include it in single one?

**Comment by MartinMystikJonas** [comment]
I just noticed that master already has fixes I need. They are just not released.  :-)

**Comment by MartinMystikJonas** [comment]
So anyhow what do you think about my proposed changes above?

**Comment by MartinMystikJonas** [comment]
See PR #8
